Repository R2D2-2019/r2d2-python-build, pull requests merged in 2019-05, with the labels that each got.

#21 Feature pylint config
  .pylintrc
  client/__pycache__/client.cpython-36.pyc
  client/__pycache__/comm.cpython-36.pyc
  common/__pycache__/common.cpython-36.pyc
  common/common.py
  manager/manager.py
  modules/button_module/main.py
  tooling/frame_generator.py
Labels: enhancement

#22 Fix/documentation
  .pylintrc
  client/comm.py
  common/common.py
  manager/manager.py
  modules/button_module/main.py
  modules/button_module/module/mod.py
  modules/controller_module/main.py
  modules/controller_module/module/mod.py
  modules/led_module/main.py
  modules/led_module/module/mod.py
  modules/template/main.py
  tooling/frame_generator.py
Labels: enhancement

#29 added pytest test files
  tooling/frame_generator.py
  tooling/test_frame_generator.py
Labels: enhancement

#31 Feature cli command frame parser
  common/frame_enum.py
  common/frames.py
  tooling/frame_generator.py
  tooling/test_frame_generator.py
Labels: enhancement

#35 fix documention startting manager.py
  README.md
Labels: documentation

#37 comment parse regex fix
  tooling/frame_generator.py
  tooling/test_frame_generator.py
Labels: bug

#42 Allow frame_type and frame_id in definition
  tooling/frame_generator.py
Labels: enhancement

#44 changed the syntax of generated-members in .pylintrc
  .pylintrc
Labels: bug

#45 Feature refactor frame generator
  common/frame_enum.py
  common/frames.py
  tooling/frame_generator.py
  tooling/test_frame_generator.py
Labels: enhancement

#53 Feature string size
  common/frame_enum.py
  common/frames.py
  tooling/frame_generator.py
  tooling/test_frame_generator.py
Labels: enhancement

#49 Feature add pytests
  .pylintrc
  common/common.py
  common/frame_enum.py
  common/frames.py
  tests/mock_client_comm.py
  tests/test_frames.py
  tests/test_tooling_frame_generator.py
  tooling/frame_generator.py
Labels: enhancement
